-- ESG Reporting Database Setup
-- Run this script to create the required Snowflake infrastructure

-- Create database
CREATE DATABASE IF NOT EXISTS ESG_REPORTING;

-- Create schemas
CREATE SCHEMA IF NOT EXISTS ESG_REPORTING.PROD;
CREATE SCHEMA IF NOT EXISTS ESG_REPORTING.STAGING;

-- Create warehouse
CREATE WAREHOUSE IF NOT EXISTS ESG_WH
    WITH WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

-- Set context
USE DATABASE ESG_REPORTING;
USE SCHEMA PROD;
USE WAREHOUSE ESG_WH;
